### ISSUE TITLE
this demo does not work

### ISSUE THREAD

**Issue by smiklosovic** [wildfly-swarm/example-jaxrs-cdi#1]
build against https://github.com/wildfly-swarm/wildfly-swarm/commit/05f9248852cd548b3a72f2a19d374d4bb21e0ea6

http://pastebin.com/raw.php?i=FBFT9PFQ

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /home/smikloso/devel/apache-maven-3.3.3
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /home/smikloso/devel/java1.8/jdk1.8.0_45/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.11.10-100.fc18.x86_64", arch: "amd64", family: "unix"

**Comment by kenfinnigan** [comment]
@smiklosovic apologies, this demo was uploaded to share between @bobmcwhirter and I, not to indicate it works.

I'm working on fixes right now

**Comment by smiklosovic** [comment]
@kenfinnigan fingers crossed! thanks for your effort

**Comment by smiklosovic** [comment]
you guys rock
